### ISSUE TITLE
Please open a PR with your changes?

### ISSUE THREAD

**Issue by ryanneufeld** [catrielmuller/Prusa-Firmware#2]
Hi there,

I'm one of the maintainers of the PrusaMK2Users org. I heard about this through the grapevine and wanted to invite you to open a PR with your changes here: 

https://github.com/PrusaMK2Users/Prusa-Firmware

Also you can reach me on twitter \@ryanneufeld, or if you go to https://3dprinting.community and join our mattermost community, we can chat about it there and see how we can make this super useful!

**Comment by catrielmuller** [comment]
I will contact you on MatterMost
There is the PR: https://github.com/PrusaMK2Users/Prusa-Firmware/pull/1
